version: "3.7"
services:
  product-service:
    container_name: product-service
    image: completed0728/product-service:1.0
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.config.import: optional:configserver:http://config-server:8888
      management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.datasource.url: jdbc:mysql://mysql:3306/products?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      logging.file: /api-logs/product-ws.log
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: benefits-network
