version: "3.7"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/suhanlee/Desktop/msa-project/prometheus-2.45.2.darwin-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: benefits-network
