version: "3.7"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /Users/suhanlee/Desktop/msa-project/grafana-v10.2.3/data:/var/lib/grafana
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: benefits-network
